// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Category } from '../../../api/category/content-types/category/category';
import { Category_Plain } from '../../../api/category/content-types/category/category';

export interface ArticleSection {
  content?: string;
  featured_image?: { data: Media };
  images?: { data: Media[] };
  product_categories: { data: Category[] };
}
export interface ArticleSection_Plain {
  content?: string;
  featured_image?: Media;
  images?: Media[];
  product_categories: Category_Plain[];
}

export interface ArticleSection_NoRelations {
  content?: string;
  featured_image?: number;
  images?: number[];
  product_categories: number[];
}

