// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface ArticleSection {
  content?: string;
  featured_image?: { data: Media };
  images?: { data: Media[] };
}
export interface ArticleSection_Plain {
  content?: string;
  featured_image?: Media;
  images?: Media[];
}

export interface ArticleSection_NoRelations {
  content?: string;
  featured_image?: number;
  images?: number[];
}

