// Interface automatically generated by schemas-to-ts

import { Page } from '../../../page/content-types/page/page';
import { Category } from '../../../category/content-types/category/category';
import { Page_Plain } from '../../../page/content-types/page/page';
import { Category_Plain } from '../../../category/content-types/category/category';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Navigation {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    url?: string;
    children: { data: Navigation[] };
    parent?: { data: Navigation };
    icon?: any;
    order?: number;
    subtitle?: string;
    page?: { data: Page };
    category?: { data: Category };
    locale: string;
    localizations?: { data: Navigation[] };
  };
}
export interface Navigation_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  url?: string;
  children: Navigation_Plain[];
  parent?: Navigation_Plain;
  icon?: any;
  order?: number;
  subtitle?: string;
  page?: Page_Plain;
  category?: Category_Plain;
  locale: string;
  localizations?: Navigation[];
}

export interface Navigation_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  url?: string;
  children: number[];
  parent?: number;
  icon?: any;
  order?: number;
  subtitle?: string;
  page?: number;
  category?: number;
  locale: string;
  localizations?: Navigation[];
}

export interface Navigation_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  url?: string;
  children: AdminPanelRelationPropertyModification<Navigation_Plain>;
  parent?: AdminPanelRelationPropertyModification<Navigation_Plain>;
  icon?: any;
  order?: number;
  subtitle?: string;
  page?: AdminPanelRelationPropertyModification<Page_Plain>;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  locale: string;
  localizations?: Navigation[];
}
