// Interface automatically generated by schemas-to-ts

import { Article } from '../../../article/content-types/article/article';
import { Page } from '../../../page/content-types/page/page';
import { ArticleCategory } from '../../../article-category/content-types/article-category/article-category';
import { Article_Plain } from '../../../article/content-types/article/article';
import { Page_Plain } from '../../../page/content-types/page/page';
import { ArticleCategory_Plain } from '../../../article-category/content-types/article-category/article-category';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Navigation {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    url?: string;
    children: { data: Navigation[] };
    parent?: { data: Navigation };
    icon?: any;
    order?: number;
    subtitle?: string;
    articles: { data: Article[] };
    page?: { data: Page };
    article_categories: { data: ArticleCategory[] };
    locale: string;
    localizations?: { data: Navigation[] };
  };
}
export interface Navigation_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  url?: string;
  children: Navigation_Plain[];
  parent?: Navigation_Plain;
  icon?: any;
  order?: number;
  subtitle?: string;
  articles: Article_Plain[];
  page?: Page_Plain;
  article_categories: ArticleCategory_Plain[];
  locale: string;
  localizations?: Navigation[];
}

export interface Navigation_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  url?: string;
  children: number[];
  parent?: number;
  icon?: any;
  order?: number;
  subtitle?: string;
  articles: number[];
  page?: number;
  article_categories: number[];
  locale: string;
  localizations?: Navigation[];
}

export interface Navigation_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  url?: string;
  children: AdminPanelRelationPropertyModification<Navigation_Plain>;
  parent?: AdminPanelRelationPropertyModification<Navigation_Plain>;
  icon?: any;
  order?: number;
  subtitle?: string;
  articles: AdminPanelRelationPropertyModification<Article_Plain>;
  page?: AdminPanelRelationPropertyModification<Page_Plain>;
  article_categories: AdminPanelRelationPropertyModification<ArticleCategory_Plain>;
  locale: string;
  localizations?: Navigation[];
}
