// Interface automatically generated by schemas-to-ts

export interface ArticleTag {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    label: string;
    locale: string;
    localizations?: { data: ArticleTag[] };
  };
}
export interface ArticleTag_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  label: string;
  locale: string;
  localizations?: ArticleTag[];
}

export interface ArticleTag_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  label: string;
  locale: string;
  localizations?: ArticleTag[];
}

export interface ArticleTag_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  label: string;
  locale: string;
  localizations?: ArticleTag[];
}
