// Interface automatically generated by schemas-to-ts

import { Navigation } from '../../../navigation/content-types/navigation/navigation';
import { Article } from '../../../article/content-types/article/article';
import { Navigation_Plain } from '../../../navigation/content-types/navigation/navigation';
import { Article_Plain } from '../../../article/content-types/article/article';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface ArticleCategory {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description?: string;
    slug?: string;
    navigation_item?: { data: Navigation };
    articles: { data: Article[] };
  };
}
export interface ArticleCategory_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  navigation_item?: Navigation_Plain;
  articles: Article_Plain[];
}

export interface ArticleCategory_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  navigation_item?: number;
  articles: number[];
}

export interface ArticleCategory_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  navigation_item?: AdminPanelRelationPropertyModification<Navigation_Plain>;
  articles: AdminPanelRelationPropertyModification<Article_Plain>;
}
