// Interface automatically generated by schemas-to-ts

import { Navigation } from '../../../navigation/content-types/navigation/navigation';
import { Navigation_Plain } from '../../../navigation/content-types/navigation/navigation';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Page {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    navigation_item?: { data: Navigation };
  };
}
export interface Page_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  navigation_item?: Navigation_Plain;
}

export interface Page_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  navigation_item?: number;
}

export interface Page_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  navigation_item?: AdminPanelRelationPropertyModification<Navigation_Plain>;
}
