// Interface automatically generated by schemas-to-ts

export interface Seo {
  meta_title: string;
  meta_description?: string;
}
export interface Seo_Plain {
  meta_title: string;
  meta_description?: string;
}

export interface Seo_NoRelations {
  meta_title: string;
  meta_description?: string;
}

