// Interface automatically generated by schemas-to-ts

export interface Feed {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    advertiser_id?: string;
    advertiser_name?: string;
    primary_region?: string;
    membership_status?: string;
    feed_id: string;
    feed_name?: string;
    language?: string;
    vertical?: string;
    last_imported?: string;
    last_checked?: string;
    no_of_products?: string;
    url?: string;
  };
}
export interface Feed_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  advertiser_id?: string;
  advertiser_name?: string;
  primary_region?: string;
  membership_status?: string;
  feed_id: string;
  feed_name?: string;
  language?: string;
  vertical?: string;
  last_imported?: string;
  last_checked?: string;
  no_of_products?: string;
  url?: string;
}

export interface Feed_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  advertiser_id?: string;
  advertiser_name?: string;
  primary_region?: string;
  membership_status?: string;
  feed_id: string;
  feed_name?: string;
  language?: string;
  vertical?: string;
  last_imported?: string;
  last_checked?: string;
  no_of_products?: string;
  url?: string;
}

export interface Feed_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  advertiser_id?: string;
  advertiser_name?: string;
  primary_region?: string;
  membership_status?: string;
  feed_id: string;
  feed_name?: string;
  language?: string;
  vertical?: string;
  last_imported?: string;
  last_checked?: string;
  no_of_products?: string;
  url?: string;
}
