debug: true
source:
  type: postgres
  host: localhost
  port: 5432
  user: admin
  password: Dominim123_!
  database: db
meilisearch:
  api_url: http://localhost:7700
  api_key: 7510VwYWCmVuVeZXzCj6bc49T6knJVk3TGiaSjZidS8
  insert_size: 500
  insert_interval: 3600
sync:
  - table: items
    index: item
    full: true
  - table: categories
    index: category
    full: true
