database_type: postgres
database_url: postgresql://postgres:YOUR_DB_PASSWORD@YOUR_DB_HOST:5432/YOUR_DB_NAME
meilisearch_url: http://YOUR_MEILISEARCH_HOST:7700
meilisearch_api_key: YOUR_MEILISEARCH_API_KEY
indexes:
  - name: your_index_name
    primary_key: id
    schema: public
    table: your_table_name
