debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: postgres
  host:
  port: 5432
  user: postgres
  password:
  database: db
meilisearch:
  api_url: https://meilisearch.webqube.de
  api_key:
  insert_size: 1000
  insert_interval: 10
sync:
  - table: items
    index: item
    plugins:
      - meilisync.plugin.Plugin
    full: true
