debug: true
plugins:
  - meilisync.plugin.Plugin
progress:
  type: file
source:
  type: postgres
  host: 65.108.149.184
  port: 5555
  user: postgres
  password: f733bccf1a6724335d12cb935c88ff18
  database: postgres
meilisearch:
  api_url: https://meilisearch.webqube.de
  api_key: 7f81143476eec1521adbdb5ab3f02894a8a4ea05c0a2efdcd7e64dd533ec4a58
  insert_size: 1000
  insert_interval: 10
sync:
  - table: items
    index: item
    plugins:
      - meilisync.plugin.Plugin
    full: true
