// Interface automatically generated by schemas-to-ts

import { ArticleCategory } from '../../../article-category/content-types/article-category/article-category';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Navigation } from '../../../navigation/content-types/navigation/navigation';
import { ArticleCategory_Plain } from '../../../article-category/content-types/article-category/article-category';
import { Navigation_Plain } from '../../../navigation/content-types/navigation/navigation';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Category {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    parent_categories?: { data: Category[] };
    child_categories?: { data: Category[] };
    cat1?: string;
    identifier: string;
    cat2?: string;
    cat3?: string;
    isCategory?: boolean;
    ignored?: boolean;
    article_categories: { data: ArticleCategory[] };
    image?: { data: Media };
    content?: string;
    navigation_item?: { data: Navigation };
    summary?: string;
  };
}
export interface Category_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  parent_categories?: Category_Plain[];
  child_categories?: Category_Plain[];
  cat1?: string;
  identifier: string;
  cat2?: string;
  cat3?: string;
  isCategory?: boolean;
  ignored?: boolean;
  article_categories: ArticleCategory_Plain[];
  image?: Media;
  content?: string;
  navigation_item?: Navigation_Plain;
  summary?: string;
}

export interface Category_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  parent_categories?: number[];
  child_categories?: number[];
  cat1?: string;
  identifier: string;
  cat2?: string;
  cat3?: string;
  isCategory?: boolean;
  ignored?: boolean;
  article_categories: number[];
  image?: number;
  content?: string;
  navigation_item?: number;
  summary?: string;
}

export interface Category_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  parent_categories?: AdminPanelRelationPropertyModification<Category_Plain>;
  child_categories?: AdminPanelRelationPropertyModification<Category_Plain>;
  cat1?: string;
  identifier: string;
  cat2?: string;
  cat3?: string;
  isCategory?: boolean;
  ignored?: boolean;
  article_categories: AdminPanelRelationPropertyModification<ArticleCategory_Plain>;
  image?: AdminPanelRelationPropertyModification<Media>;
  content?: string;
  navigation_item?: AdminPanelRelationPropertyModification<Navigation_Plain>;
  summary?: string;
}
