// Interface automatically generated by schemas-to-ts

export interface CategoryComponent {
  name?: string;
}
export interface CategoryComponent_Plain {
  name?: string;
}

export interface CategoryComponent_NoRelations {
  name?: string;
}

